import { useEffect, useState } from 'react';
import Head from 'next/head';
import { useAuth } from '../../context/AuthContext';
import { usePins } from '../../context/PinsContext';
import Layout from '../../components/Layout';
import MasonryLayout from '../../components/MasonryLayout';
import { useRouter } from 'next/router';

export default function CategoyPage() {
	const router = useRouter();
	const { user } = useAuth();
	const { pins } = usePins();
	const filteredPins = pins.filter((pin) => pin.category === router.query.id);

	return (
		<>
			<Head>
				<title>ConnectMe</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout user={user}>
				<h2 className='text-4xl font-bold capitalize mb-4'>
					{router.query.id}
				</h2>
				{filteredPins.length > 0 ? (
					<MasonryLayout pins={filteredPins} />
				) : (
					<p>Currently, there are no pins in this category ...</p>
				)}
			</Layout>
		</>
	);
}
