import Head from 'next/head';
import { useState } from 'react';
import PinDetails from '../../components/PinDetails';
import Layout from '../../components/Layout';
import { useAuth } from '../../context/AuthContext';

const PinDetailsPage = () => {
	return (
		<>
			<Head>
				<title>ConnectMe</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Layout>
				<PinDetails />
			</Layout>
		</>
	);
};

export default PinDetailsPage;
