import Head from 'next/head';
import { useState } from 'react';
import CreatePin from '../components/CreatePin';
import Layout from '../components/Layout';
import { useAuth } from '../context/AuthContext';

export default function Home() {
	const { currentUser } = useAuth();
	const [postText, setPostText] = useState('');
	// console.log(currentUser);

	return (
		<>
			<Head>
				<title>ConnectMe</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Layout>
				<CreatePin />
			</Layout>
		</>
	);
}
