import Head from 'next/head';
import { useAuth } from '../context/AuthContext';
import Layout from '../components/Layout';

export default function Home() {
	const { user } = useAuth();

	return (
		<>
			<Head>
				<title>ConnectMe</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout user={user}>
				<div>Hello</div>
			</Layout>
		</>
	);
}
