import { useEffect, useState } from 'react';
import Head from 'next/head';
import { useAuth } from '../context/AuthContext';
import { usePins } from '../context/PinsContext';
import Layout from '../components/Layout';
import MasonryLayout from '../components/MasonryLayout';

export default function Feed() {
	const { user } = useAuth();
	const { pins } = usePins();

	return (
		<>
			<Head>
				<title>ConnectMe</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout user={user}>
				<MasonryLayout pins={pins} />
			</Layout>
		</>
	);
}
